version: '3.3'

services:
  web-app:
    
    image: ap88/flask-k8-app:005

    build: .
    
    container_name: flask-k8-app-docker
    ports:
      - "5000:5000"
    volumes:
      - ./storage:/storage
    restart: always
