apiVersion: v1
kind: Service
metadata:
  name: flask-k8-app-service
spec:
  type: NodePort
  selector:
    app: flask-k8-app
  ports:
    - protocol: TCP
      port: 5000          # The port used inside the cluster
      targetPort: 5000  # The port the app listen - inside the container
      nodePort: 30001    # The port to access the app from outside (browser)
